spring.application.name: entry-level-java-challenge

server:
  error:
    include-message: always
    include-binding-errors: always

api:
  security:
    key: some-super-secret-key # In production, this should be set via environment variable
